### ISSUE TITLE
Header values not honored for replay

### ISSUE THREAD

**Issue by eli-sumologic** [FTWynn/gologgen#15]
Header values appear to work for data generated by Headers in the gologgen.data. However, I added Headers in the gologgen.conf file and they are not being honored:

I checked this by running the debug level and verifiying the Overwritten sourcecategory is in the header when the Headers are in gologgen.data. Did the same for gologgen.conf and they are not to be found.

Here is what I have in gologgen.conf:

{
    "OutputType" : "http",
  "httpLoc" : "**masked**",
  "FileOutputPath" : "testoutput.dat",
  "DataFiles" : [
   {
      "Path": "config/gologgen.data"
   }
  ],
  "ReplayFiles" : [
   {
     "Path" : "config/copies/apache200s.data",
     "TimestampRegex" : "\d{4}-\d{2}-\d{2} (?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2})\.\d{3} -\d{4} \+\d{4}",
     "TimestampFormat" : "2006-01-02 15:04:05",
     "RepeatInterval": 8,
     "Headers" : [
        {"Header" : "Content-type",
          "Value" : "plain/text"},
        {"Header" :"X-Sumo-Category",
          "Value" : "Prod/Apache"},
        {"Header" :"X-Sumo-Name",
          "Value" : "/var/log/access.log"},
        {"Header" :"X-Sumo-Host",
          "Value" : "PhotoApp-prod-1"}
        ]
   },
   {
     "Path" : "config/copies/apache500s.data",
     "TimestampRegex" : "\d{4}-\d{2}-\d{2} (?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2})\.\d{3} -\d{4} \+\d{4}",
     "TimestampFormat" : "2006-01-02 15:04:05",
     "RepeatInterval": 300,
     "Headers" : [
        {"Header" : "Content-type",
          "Value" : "plain/text"},
        {"Header" :"X-Sumo-Category",
          "Value" : "Prod/Apache"},
        {"Header" :"X-Sumo-Name",
          "Value" : "/var/log/access.log"},
        {"Header" :"X-Sumo-Host",
          "Value" : "PhotoApp-prod-1"}
        ]
   }
  ]
 }

**Comment by FTWynn** [comment]
Version bump solved the problem, though I should probably make versions more visible
