### ISSUE TITLE
Add line number syntax errors to gologgen.data output

### ISSUE THREAD

**Issue by eli-sumologic** [FTWynn/gologgen#9]
I can't figure out the right syntax for gologgen.data even with examples. I'm just bad with the [,{,:,"-ish characters. If you provided a specific line number where the syntax problem is with the file, it would be really helpful. Here's an example of the current generic error message and I still haven't found the syntax issue I have:

arguments by adding nil"root@ip-172-31-0-119:/home/eli/loggen/gologgen# ./gologgen_linux_amd64 
EROR[02-03|21:14:58] Something went amiss on parsing the data file:  function=main.storeDataFileLogLines LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"

**Comment by FTWynn** [comment]
It looks like this is actually not an easy thing to do at all in Go. 

What I've done instead is added a suggestion to the error message to confirm that the config is valid JSON (the most likely problem at this step). We'll see if that keeps it from popping up moving forward.
